### ISSUE TITLE
ModuleNotFoundError: No module named 'openvino.runtime'

### ISSUE THREAD

**Issue by betogulliver** [openvinotoolkit/model_analyzer#50]
After following the installation steps 

	pip install -U openvino-dev

       git clone https://github.com/openvinotoolkit/model_analyzer

and try to run the example

python model_analyzer.py  --model ../public/mobilenet-v2/FP16/mobilenet-v2.xml --ignore-unknown-layers

if got the following error 

Traceback (most recent call last):
  File "model_analyzer.py", line 16, in <module>
    from model_analyzer import main, parse_arguments
  File "/private/tmp/ovino/model_analyzer/model_analyzer/__init__.py", line 16, in <module>
    from model_analyzer.uncounted_layers import *
  File "/private/tmp/ovino/model_analyzer/model_analyzer/uncounted_layers.py", line 22, in <module>
    from openvino.runtime import Node
ModuleNotFoundError: No module named 'openvino.runtime'

my openvino version is  

openvino                  2021.4.2                 pypi_0    pypi

any ideas?

**Comment by artyomtugaryov** [comment]
Hello @betogulliver,

Thank you for using Model Analyzer.

The master branch of the tool is working with the master branch of the OpenVINO repository and Model Analyzer on the latest master uses OpenVINO 2.0 API and does not support OpenVINO from the previous releases.

As I understand you use openvino 2021.4.2 and we suggest using Model Analyzer from the releases/2021/4.2 branch. So, you need to change the branch after cloning the Model Analyzer repo:
```sh
git checkout releases/2021/4.2
```

The `releases/2021/4.2` should work with OpenVINO 2021.4.2.

Let me know if you will have any problems with the tool.

**Comment by morkovka1337** [comment]
> The master branch of the tool is working with the master branch of the OpenVINO repository and Model Analyzer on the latest master uses OpenVINO 2.0 API and does not support OpenVINO from the previous releases.

Could you, please, specify this in the requirements on the main page of the repo or something (preferably in the header of the readme), this is not obvious at all. I had to change some lines of the code to make it able to be run, and a couple of my colleagues also fell into this trap.

**Comment by artyomtugaryov** [comment]
Hello @morkovka1337 ,

Sure, will create a PR

**Comment by artyomtugaryov** [comment]
@morkovka1337 we added the disclaimer about compatibility with the [OpenVINO repository](https://github.com/openvinotoolkit/openvino) to the [DEVELOPER.md](https://github.com/openvinotoolkit/model_analyzer/blob/master/DEVELOPER.md)
